export class RoutesLists
{
    public static ssrRoutes:string[] = [
    '/dashboard',
    '/appcustomerprofile',
    '/twofactorauth', 
     '/signin',
    '/uploadnetpay', 
    '/forgetpwrd',
     '/forgetpwrd2', 
     '/HubTeamListByNameMember',
     'AllOngoingAndCompletedLoanAppList',
    '/appclientrequest', 
    '/HubTeamMembersByGroupId',
    '/AllOngoingAndCompletedLoanAppList',
    '/HubTeamMembers',
    '/AllDisbursedLoanAppList',
    '/HubTeamsDisbursmentOfficers',
    '/HubTeamListByNameMember',
    '/AllDisbursedLoanAppList',
    '/AllOngoingAndCompletedLoanAppList',
    '/appprofile', 
     '/apppasswordreststatus', 
     '/appclientmonthlynetpays', 
   '/appeditprofile',
    '/appmonthlynetpays', 
    '/apploandetails', 
    '/apploanprocess', 
    '/apploantenure',
    'apploantenures', 
   '/loanapps', 
    '/appaddstaff', 
     '/appstaffs',
   '/appdashboardpassword', 
    '/appstaffspermission', 
     '/apploandue', 
   '/appportalnotices', 
    '/appsettings', 
     '/appclients', 
     '/hubTeams',
    '/newHubTeam', 
   '/HubTeamMembers', 
     '/CreateHubTeamMember', 
     '/disbursementTeams', 
    '/teamMembersByGroup', 
     '/assignLoanToTeamMember',
     '/disbursedLoans', 
    '/repaymentloans', 
     '/repayments',
   '/narrations', 
     '/narrationlist', 
    '/editteammemberpermission', 
    '/myPerissions', 
    '/loanHistory',       
      '/CalculateScheduledLoanAmount',
    '/AllDashboardLoanAppList',
    '/HubTeamList',
      '/SetLoanPrinterArrangement',
      '/AdmindashboardLoanApp',
     '/AllLoanAppList' ,
    '/AdminLoanMethodList' ,
      '/ListOfNarrationList' ,
   '/AllStaffList',
   '/StaffAccessRight' ,
   '/LoanAppDetails' ,
    '/GetHubTeam',
     '/ExitNewHubTeamMember',
    '/AdminActivateLoanMethod',
    '/ProcessAction',
     '/ProcessAction2',
      '/ProcessAction3',
    '/ProcessAction5',
     '/ProcessAction6',
      '/ProcessAction1',
      '/ProcessGetAllStaffAccessRight' ,
     '/GetE360UsersByTeamMember' ,
     '/ProcessSetPermissionToCreatedStaff',
    '/ProcessSetPermissionHasPermissionToDisableStaff',
     '/CancelLoanAppRequest',
     '/AdminCancelLoanAppRequest',
      '/AdminApprovedLoanAppRequest',
     '/AdminSaveLoanMethod',
     '/NewNarration',
     '/CreateHubTeam',
     '/CreateNewHubTeamMember',
    '/OfficerStandardLoan',
   '/UpdateLoanSettings',
      '/RegisterStaffs',
      '/AdminSignInAuth',
    '/AutoAdminCreateAcct' ,
     '/ConfirmTwoFactorAuth',
      '/LoadSpinnerRound' ,
     '/ReSendTwoFactorCode' ,
     '/ClientNetPay1',
    '/ClientNetPay',
    '/ActivateCustomerLoanPermission' ,
     '/ActivateHubGroup',
      '/ActivateHubTeamMember' ,
     '/ActivateHubGroup',
    '/ActivateTeamLead',
     '/ActivateReconciliationOfficerMember',
    '/AllMonthlyNetPays',
     '/GetUserProfileDetails',
     '/GetUserPermissionDetails' ,
     '/GetLoanSettings' ,
    '/GetAllReconcilationMembers',
    '/ClientMonthlyNetPays',
     '/DeleteClientNetPay' ,
     '/CheckIfEmailExit',
      '/ChangePassword' ,
   '/InnerChangePassword',
   '/ExportApprovedLoanApps',
   '/FetchAccountDetails',
   '/UserTwoFactorActivator',
        '/ChangeProfileDetails'];
}
